#!/usr/bin/env bun

import { $ } from 'bun';

const formulae = (await $`brew list --formulae`.text())
  .split('\n')
  .filter((x) => x.length > 0);

const results = await Promise.all(formulae.map(async (formula) => {
  const dependents = (await $`brew uses --recursive --installed ${formula}`.text()).split('\n');
  return { formula, dependents };
}));

results.forEach((result) => {
  console.log(result.formula);
  result.dependents.forEach((dependent) => {
    console.log(`  ${dependent}`);
  });
});
