#!/usr/bin/env -S deno run

const msFromNow = Number(Deno.args[0]) * 24 * 60 * 60 * 1000;
const today = Date.now();

const target = new Date(today + msFromNow).toISOString();

console.log(target.substring(0, 10));
