#!/usr/bin/env python3

from datetime import datetime
import sys

day1 = datetime.strptime(sys.argv[1], "%Y-%m-%d")
day2 = datetime.strptime(sys.argv[2], "%Y-%m-%d")
delta = day1 - day2

print(abs(delta.days))
