#!/usr/bin/env bun

const msFromNow = Number(process.argv[2]) * 24 * 60 * 60 * 1000;
const today = Date.now();

const target = new Date(today + msFromNow).toISOString();

console.log(target.substring(0, 10));
