#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "js-to-json-logic>=0.1.0",
# ]
# ///

from js_to_json_logic import transform_js


if __name__ == "__main__":
    import json
    import sys

    if len(sys.argv) != 2:
        print("Usage: js-to-json-logic <js-expression>")
        sys.exit(1)

    js_expression = sys.argv[1]
    json_logic = transform_js(js_expression)
    print(json.dumps(json_logic, indent=2))
