#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'ostruct'
require 'uri'

begin
  tags = File.readlines("#{Dir.home}/.config/lobsters/tags").map(&:chomp)
rescue
  tags = []
end

response = Net::HTTP.get(URI('https://lobste.rs/hottest'))
stories = JSON.parse(response, object_class: OpenStruct)
lines = []

stories.each do |story|
  next unless tags.empty? or tags.intersect?(story.tags)

  lines << "#{story.title} (#{story.short_id_url})\n#{story.comment_count} comments [#{story.tags.join(', ')}]"
end

puts lines.join("\n\n")
