#!/usr/bin/env -S deno run --allow-env=HOME --allow-read --allow-net

import { existsSync } from "https://deno.land/std/fs/mod.ts";

const filePath = `${Deno.env.get("HOME")}/.config/lobsters/tags`;
let tags = [];

if (existsSync(filePath)) {
  tags = Deno.readTextFileSync(filePath).trim().split("\n");
}

const stories = await fetch("https://lobste.rs/hottest").then((res) =>
  res.json()
);
let lines = [];

for (const story of stories) {
  const foundTags = tags.filter((tag) => story.tags.includes(tag));
  if (tags.length === 0 || foundTags.length > 0) {
    lines.push(
      `${story.title} (${story.short_id_url})\n${
        story.comment_count
      } comments [${story.tags.join(", ")}]`
    );
  }
}

console.log(lines.join("\n\n"));
