#!/usr/bin/env -S uv run --script

# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "beautifulsoup4>=4.14.3",
#     "httpx>=0.28.1",
# ]
# ///

import sys

from bs4 import BeautifulSoup
import httpx


def skip(meta):
    if meta.get("name") is None and meta.get("property") is None:
        return True
    elif meta.get("name") in ["viewport", "robots"]:
        return True
    else:
        return False


url = sys.argv[1]
resp = httpx.get(url)
soup = BeautifulSoup(resp.text, "html.parser")

metas = [meta for meta in soup.find_all("meta") if not skip(meta)]

for meta in metas:
    print(meta)
