#!/usr/bin/env ruby

def spongebobify(str)
  lower = false
  str.chars.map do |c|
    if c.match?(/[a-zA-Z]/)
      lower = !lower
      lower ? c.downcase : c.upcase
    else
      c
    end
  end.join
end

print spongebobify(ARGV[0])
