#!/usr/bin/env ruby

def spongebobify(str)
  lower = false
  str.chars.map do |c|
    if c =~ /[a-zA-Z]/
      lower ? lower = false : lower = true
      lower ? c.downcase : c.upcase
    else
      c
    end
  end.join
end

printf "%s", spongebobify(ARGV[0])
