#!/usr/bin/env -S deno run

function spongebob(s) {
  let lower = false;
  return s.split('').map(c => {
    if (c.match(/[a-zA-Z]/)) {
      lower = !lower;
      return lower ? c.toLowerCase() : c.toUpperCase();
    }
    return c;
  }).join('');
}

Deno.stdout.write(new TextEncoder().encode(spongebob(Deno.args[0])));
