#!/usr/bin/env python3

import optparse
from uuid import uuid7

parse = optparse.OptionParser()
parse.add_option(
    "-n",
    "--number",
    dest="number",
    default=1,
    type="int",
    help="number of UUIDs to generate",
)
options, args = parse.parse_args()

if options.number == 1:
    print(uuid7(), end="")
else:
    for _ in range(options.number):
        print(uuid7())
