#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "pandas>=3.0.1",
#     "typer>=0.24.0",
# ]
# ///

import os

import pandas as pd
import typer


def main(input_file: str, out_dir: str = "."):
    os.makedirs(out_dir, exist_ok=True)
    sheets = pd.read_excel(input_file, sheet_name=None)
    idx = 0
    for sheet_name, df in sheets.items():
        idx += 1
        out_file = os.path.join(out_dir, f"{idx} {sheet_name}.csv")
        df.to_csv(out_file, index=False)


if __name__ == "__main__":
    typer.run(main)
